flowchart TD
    start([Start]) --> CheckInstallations

    subgraph CheckInstallations[Check <font color='pink'>Building</font> Gas Installations]
        CheckNBND51001{Meets<br>NBN D 51-001?}
        CheckNBND51003{Meets<br>NBN D 51-003?}
        CheckNBND51004{Meets<br>NBN D 51-004?}
        CheckNBND51006{Meets<br>NBN D 51-006?}
    end

    CheckInstallations --> CheckNBND51001
    CheckNBND51001 -->|Yes| CheckNBND51003
    CheckNBND51001 -->|No| Fail

    CheckNBND51003 -->|Yes| CheckNBND51004
    CheckNBND51003 -->|No| Fail

    CheckNBND51004 -->|Yes| CheckNBND51006
    CheckNBND51004 -->|No| Fail

    CheckNBND51006 -->|Yes| Pass
    CheckNBND51006 -->|No| Fail

    Pass([Pass]) --> End
    Fail([Fail]) --> End
    End([End])

    style CheckNBND51001 fill:#f9f,stroke:#333,stroke-width:2px
    style CheckNBND51003 fill:#f9f,stroke:#333,stroke-width:2px
    style CheckNBND51004 fill:#f9f,stroke:#333,stroke-width:2px
    style CheckNBND51006 fill:#f9f,stroke:#333,stroke-width:2px