graph TD
    A[Start] --> B{Check <font color='pink'>Building</font>}
    B --> C{Check <font color='pink'>Building</font> <font color='blue'>Amount of storeys</font>}
    C --> |Amount of storeys > 1| D{Check <font color='pink'>Compartment</font>}
    C --> |Amount of storeys <= 1| E[Pass: No compartmentation required]
    D --> F{Check <font color='pink'>Compartment</font> <font color='blue'>Area</font>}
    F --> |Area > 2000 m2| G[Fail: Compartmentation required]
    F --> |Area <= 2000 m2| H[Pass: No compartmentation required]
    D --> I{Check <font color='pink'>Compartment</font> <font color='blue'>Occupancy</font>}
    I --> |Occupancy > 50| J[Fail: Compartmentation required]
    I --> |Occupancy <= 50| K[Pass: No compartmentation required]
    D --> L{Check <font color='pink'>Compartment</font> <font color='blue'>Has nighttime occupancy?</font>}
    L --> |Yes| M[Fail: Compartmentation required]
    L --> |No| N[Pass: No compartmentation required]
    D --> O{Check <font color='pink'>Compartment</font> <font color='blue'>Is Parking?</font>}
    O --> |Yes| P[Fail: Compartmentation required]
    O --> |No| Q[Pass: No compartmentation required]
    D --> R{Check <font color='pink'>Wall</font> <font color='blue'>Compartmentation</font>}
    R --> |Compartmentation = true| S[Pass: Wall is compartmented]
    R --> |Compartmentation = false| T[Fail: Wall is not compartmented]
    D --> U{Check <font color='pink'>Door</font> <font color='blue'>Compartmentation</font>}
    U --> |Compartmentation = true| V[Pass: Door is compartmented]
    U --> |Compartmentation = false| W[Fail: Door is not compartmented]