graph TD
    start([Start]) --> check_wall[/"Check each <font color='pink'>Wall</font>"/]
    check_wall --> penetrations{{"Are there any penetrations<br>for fluids or electricity?"}}
    penetrations -->|Yes| check_penetrations[/"Check each penetration"/]
    penetrations -->|No| check_expansion_joints{{"Are there any<br>expansion joints?"}}
    check_penetrations --> affect_fire_resistance{{"Does the penetration adversely<br>affect the required <font color='blue'>fire resistance</font>?"}}
    affect_fire_resistance -->|Yes| fail([Fail])
    affect_fire_resistance -->|No| check_expansion_joints
    check_expansion_joints -->|Yes| check_joints[/"Check each expansion joint"/]
    check_expansion_joints -->|No| pass([Pass])
    check_joints --> affect_fire_resistance_joints{{"Does the expansion joint adversely<br>affect the required <font color='blue'>fire resistance</font>?"}}
    affect_fire_resistance_joints -->|Yes| fail
    affect_fire_resistance_joints -->|No| pass
    style start fill:#green
    style fail fill:#red
    style pass fill:#green