flowchart TD
    S1["Start: Suspended Ceiling Check"] --> A{"Is space between <a href='http://example.com/firebimbuilding#Ceiling' style='color:pink;'>Ceiling</a> and suspended ceiling equipped with automatic fire extinguishing system?"}
    A -- Yes --> B[/"Pass"/]
    A -- No --> C{"Check horizontal projection of space"}
    C --> D{"Can space be inscribed in a square with side ≤ 25m?"}
    D -- Yes --> E[/"Pass"/]
    D -- No --> F{"Is space divided into volumes?"}
    F -- Yes --> G{"For each dividing vertical screen"}
    F -- No --> H[/"Fail"/]
    G --> I{"Is screen <a href='http://example.com/firebimbuilding#Material' style='color:blue;'>Material</a> <a href='http://example.com/firebimbuilding#FireReaction' style='color:blue;'>Fire reaction</a> class A1 and/or A2-s1,d0?"}
    I -- Yes --> J{"Does screen cover entire space between pipes?"}
    I -- No --> K[/"Fail"/]
    J -- Yes --> L{"Does screen have <a href='http://example.com/firebimbuilding#FireResistance' style='color:blue;'>Fire resistance</a> EI 30?"}
    J -- No --> K
    L -- Yes --> M[/"Pass"/]
    L -- No --> K
     S1:::startClass
     B:::passClass
     E:::passClass
     H:::failClass
     K:::failClass
     M:::passClass
    classDef startClass fill:#f9f,stroke:#333,stroke-width:4px
    classDef passClass fill:#9f9,stroke:#333,stroke-width:2px
    classDef failClass fill:#f99,stroke:#333,stroke-width:2px