flowchart TD
    A[Start] --> B{Check <font color='pink'>Building</font>}
    B --> C{<font color='pink'>Building</font> <font color='blue'>Amount of storeys</font> > 2?}
    C -->|Yes| D[Check all <font color='pink'>Compartment</font>s]
    C -->|No| E[Rule not applicable]
    D --> F{For each <font color='pink'>Compartment</font>}
    F --> G{<font color='pink'>Compartment</font> <font color='blue'>Area</font> > 800 m2?}
    G -->|Yes| H[Compartment fails]
    G -->|No| I[Compartment passes]
    I --> J{More <font color='pink'>Compartment</font>s?}
    J -->|Yes| F
    J -->|No| K[All compartments checked]
    H --> L[Fail]
    K --> M{Any failures?}
    M -->|Yes| L
    M -->|No| N[Pass]
    E --> O[End]
    L --> O
    N --> O