graph TD
    start([Start])
    -->check{{"Check if <font color='pink'>Building</font> has electrical installations"}}
    check -->|Yes| verify{{"Verify if electrical installations comply with A.R.E.I."}}
    check -->|No| pass([Pass])
    verify -->|Compliant| pass
    verify -->|Non-compliant| fail([Fail])
    
    classDef object fill:#ffc0cb,stroke:#333,stroke-width:2px;
    classDef property fill:#add8e6,stroke:#333,stroke-width:2px;
    class Building object;