flowchart TD
    start[Start] --> A
    A{For each `:::pink Compartment`:::}
    A -->|Yes| B{`:::blue Is Classroom?`:::}
    A -->|No| End
    B -->|Yes| C[Get `:::blue Area`:::]
    B -->|No| End
    C --> D{`:::blue Area`:::  ≤ 100 m²}
    D -->|Yes| E[Pass]
    D -->|No| F{`:::blue Area`:::  ≤ 200 m²}
    F -->|Yes| G{`:::blue Number of exits`:::  ≥ 2}
    F -->|No| H[Fail]
    G -->|Yes| I[Pass]
    G -->|No| J[Fail]
    E --> End
    I --> End
    H --> End
    J --> End
    End[End]

classDef pink fill:#FFC0CB,stroke:#333,stroke-width:2px;
classDef blue fill:#ADD8E6,stroke:#333,stroke-width:2px;