graph TD
    Start[Start] --> CheckStair{Check <font color='pink'>Stair</font>}
    CheckStair --> |For each <font color='pink'>Stair</font>| IsExternal{Is <font color='pink'>Stair</font> external?}
    IsExternal --> |Yes| CheckElevation{Check <font color='blue'>Elevation</font>}
    CheckElevation --> |Leads to evacuation level| CheckMaterial{Check <font color='blue'>Material</font>}
    CheckMaterial --> |<font color='blue'>Material</font> is class A1| CheckConnection{Check connection to <font color='pink'>Compartment</font>}
    CheckConnection --> |via <font color='pink'>Door</font>| Pass[Pass]
    CheckConnection --> |via <font color='pink'>Space</font> labeled as escape terrace| Pass
    CheckConnection --> |Other| Fail[Fail]
    IsExternal --> |No| Fail
    CheckElevation --> |Does not lead to evacuation level| Fail
    CheckMaterial --> |<font color='blue'>Material</font> is not class A1| Fail
    Pass --> CheckNextLevel{Check connection to next level}
    CheckNextLevel --> |via retractable or folding stairs| Pass2[Pass]
    CheckNextLevel --> |Other| Fail
    Fail --> End[End]
    Pass2 --> End