graph TD
    start([Start]) --> checkWalls{{"Check <font color='pink'>Wall</font>s forming rooms or groups of rooms"}}
    checkWalls -->|For each wall| checkFireResistance{{"Is <font color='blue'>Fire resistance</font> equal to compartment walls?"}}
    checkFireResistance -->|Yes| checkNextWall[Check next wall]
    checkFireResistance -->|No| fail1[Fail: Wall does not meet fire resistance requirement]
    checkNextWall --> checkMoreWalls{{"More walls to check?"}}
    checkMoreWalls -->|Yes| checkWalls
    checkMoreWalls -->|No| checkOpenings[Check openings in vertical walls]
    checkOpenings --> checkDoors{{"Check <font color='pink'>Door</font>s in openings"}}
    checkDoors -->|For each door| checkSelfClosing{{"Is <font color='blue'>Self-closing</font> true?"}}
    checkSelfClosing -->|Yes| checkFireResistanceDoor{{"Is <font color='blue'>Fire resistance</font> EI1 30?"}}
    checkSelfClosing -->|No| fail2[Fail: Door is not self-closing]
    checkFireResistanceDoor -->|Yes| checkSwingDirection{{"Does door open in evacuation direction?"}}
    checkFireResistanceDoor -->|No| fail3[Fail: Door does not meet fire resistance requirement]
    checkSwingDirection -->|Yes| checkNextDoor[Check next door]
    checkSwingDirection -->|No| fail4[Fail: Door does not open in evacuation direction]
    checkNextDoor --> checkMoreDoors{{"More doors to check?"}}
    checkMoreDoors -->|Yes| checkDoors
    checkMoreDoors -->|No| checkObstructions[Check for obstructions]
    checkObstructions --> obstructionsPresent{{"Any objects hindering evacuation to exits?"}}
    obstructionsPresent -->|Yes| fail5[Fail: Objects hinder evacuation]
    obstructionsPresent -->|No| pass([Pass: All requirements met])
    fail1 --> end([End])
    fail2 --> end
    fail3 --> end
    fail4 --> end
    fail5 --> end
    pass --> end