flowchart TD
    S1["Start: Evacuation Path Check"] --> A{"For each <a href='http://example.com/firebimbuilding#EvacuationRoute' style='color:pink;'>EvacuationRoute</a>"}
    A --> B{"Is <a href='http://example.com/firebimbuilding#EvacuationRoute' style='color:pink;'>EvacuationRoute</a> through a <a href='http://example.com/firebimbuilding#Stairway' style='color:pink'>Stairway</a>?"} & I{"For every <a href='http://example.com/firebimbuilding#Door' style='color:pink'>Door</a> on <a href='http://example.com/firebimbuilding#EvacuationRoute' style='color:pink'>EvacuationRoute</a>"} & N{"Ends on <a href='http://example.com/firebimbuilding#EscapeTerrace' style='color:purple'>EscapeTerrace</a>"} & V{"Passes <a href='http://example.com/firebimbuilding#Sas' style='color:pink'>Sas</a>"}
    B -- Yes --> C{"For each <a href='http://example.com/firebimbuilding#EvacuationRoute' style='color:pink;'>EvacuationRoute</a> <a href='http://example.com/firebimbuilding#Wall' style='color:pink'>Wall</a> and each <a href='http://example.com/firebimbuilding#Stairway' style='color:pink'>Stairway</a> <a href='http://example.com/firebimbuilding#Wall' style='color:pink'>Wall</a>"}
    B -- No --> D{"For each <a href='http://example.com/firebimbuilding#EvacuationRoute' style='color:pink;'>EvacuationRoute</a> <a href='http://example.com/firebimbuilding#Wall' style='color:pink'>Wall</a>"}
    C --> F{"<a href='http://example.com/firebimbuilding#FireResistanceRating' style='color:blue'>FireResistanceRating</a> ≥ EI 30?"}
    F -- Yes --> G[/"Pass"/]
    F -- No --> H[/"Fail"/]
    K{"<a href='http://example.com/firebimbuilding#FireResistanceRating' style='color:blue;'>FireResistanceRating</a> ≥ EI1 30?"} -- Yes --> L[/"Pass"/]
    K -- No --> M[/"Fail"/]
    R{"<a href='http://example.com/firebimbuilding#FireResistanceRating' style='color:blue;'>FireResistanceRating</a> ≥ EI 60?"} -- Yes --> S[/"Pass"/]
    R -- No --> T[/"Fail"/]
    N -- No --> U[/"Pass"/]
    Z{"<a href='http://example.com/firebimbuilding#FireResistanceRating' style='color:blue;'>FireResistanceRating</a> ≥ EI 60?"} -- Yes --> AA[/"Pass"/]
    Z -- No --> AB[/"Fail"/]
    V -- No --> AC[/"Pass"/]
    D --> F
    I --> K
    N -- Yes --> P{"For each <a href='http://example.com/firebimbuilding#EscapeTerrace' style='color:purple;'>EscapeTerrace</a> <a href='http://example.com/firebimbuilding#Wall' style='color:pink'>Wall</a>"}
    X{"For each <a href='http://example.com/firebimbuilding#Sas' style='color:pink;'>Sas</a> <a href='http://example.com/firebimbuilding#Wall' style='color:pink'>Wall</a>"} --> Z
    P --> R
    V -- Yes --> X

     S1:::startClass
     G:::passClass
     H:::failClass
     L:::passClass
     M:::failClass
     S:::passClass
     T:::failClass
     U:::passClass
     AA:::passClass
     AB:::failClass
     AC:::passClass
    classDef startClass fill:#f9f,stroke:#333,stroke-width:4px
    classDef passClass fill:#9f9,stroke:#333,stroke-width:2px
    classDef failClass fill:#f99,stroke:#333,stroke-width:2px
    classDef continueClass fill:#FFD600,stroke:#333,stroke-width:2px