graph TD
    A[Start] --> B{Check <font color='pink'>Compartment</font>}
    B --> C{Is <font color='blue'>Is Classroom?</font> true?}
    C -->|Yes| D[Classify as Evacuation Room]
    C -->|No| E{Is <font color='blue'>Has nighttime occupancy?</font> true?}
    E -->|Yes| D
    E -->|No| F{Is <font color='blue'>Is Parking?</font> true?}
    F -->|No| D
    F -->|Yes| G[Not an Evacuation Room]
    D --> H{Check <font color='blue'>Area</font>}
    H -->|Area <= 1000m2| I[Pass]
    H -->|Area > 1000m2| J[Fail]
    G --> K[End]
    I --> K
    J --> K

    style A fill:#f9f,stroke:#333,stroke-width:2px
    style B fill:#f9f,stroke:#333,stroke-width:2px
    style C fill:#bbf,stroke:#333,stroke-width:2px
    style D fill:#dfd,stroke:#333,stroke-width:2px
    style E fill:#bbf,stroke:#333,stroke-width:2px
    style F fill:#bbf,stroke:#333,stroke-width:2px
    style G fill:#fdd,stroke:#333,stroke-width:2px
    style H fill:#bbf,stroke:#333,stroke-width:2px
    style I fill:#dfd,stroke:#333,stroke-width:2px
    style J fill:#fdd,stroke:#333,stroke-width:2px
    style K fill:#f9f,stroke:#333,stroke-width:2px