graph TD
    start[Start] --> check_parking{{"Check if <font color='pink'>Compartment</font> <font color='blue'>Is Parking?</font>"}}
    check_parking -->|Yes| check_walls{{"Check <font color='pink'>Wall</font>s between parking and rest of building"}}
    check_walls -->|For each wall| check_fire_resistance{{"Is <font color='pink'>Wall</font> <font color='blue'>Fire resistance</font> >= EI 60?"}}
    check_fire_resistance -->|No| fail[Fail: Wall fire resistance insufficient]
    check_fire_resistance -->|Yes| check_connection{{"Check connection between parking and rest of building"}}
    check_connection --> check_vestibule{{"Is there a vestibule?"}}
    check_vestibule -->|Yes| check_vestibule_walls{{"Check vestibule walls"}}
    check_vestibule_walls --> check_vestibule_wall_resistance{{"Is <font color='pink'>Wall</font> <font color='blue'>Fire resistance</font> >= EI 60?"}}
    check_vestibule_wall_resistance -->|No| fail[Fail: Vestibule wall fire resistance insufficient]
    check_vestibule_wall_resistance -->|Yes| check_vestibule_doors{{"Check vestibule doors"}}
    check_vestibule_doors --> check_vestibule_door_resistance{{"Is <font color='pink'>Door</font> <font color='blue'>Fire resistance</font> >= EI1 30?"}}
    check_vestibule_door_resistance -->|No| fail[Fail: Vestibule door fire resistance insufficient]
    check_vestibule_door_resistance -->|Yes| check_vestibule_door_closing{{"Is <font color='pink'>Door</font> <font color='blue'>Self-closing</font> or self-closing in case of fire?"}}
    check_vestibule_door_closing -->|No| fail[Fail: Vestibule door not self-closing]
    check_vestibule_door_closing -->|Yes| pass[Pass: Vestibule meets requirements]
    check_vestibule -->|No| check_single_door{{"Check single door connection"}}
    check_single_door --> check_single_door_resistance{{"Is <font color='pink'>Door</font> <font color='blue'>Fire resistance</font> >= EI1 60?"}}
    check_single_door_resistance -->|No| fail[Fail: Single door fire resistance insufficient]
    check_single_door_resistance -->|Yes| check_single_door_closing{{"Is <font color='pink'>Door</font> <font color='blue'>Self-closing</font> or self-closing in case of fire?"}}
    check_single_door_closing -->|No| fail[Fail: Single door not self-closing]
    check_single_door_closing -->|Yes| pass[Pass: Single door meets requirements]
    check_parking -->|No| pass[Pass: Not a parking compartment, rule does not apply]